### ISSUE TITLE
Processing doesn't work on first login

### ISSUE THREAD

**Issue by adamb70** [adamb70/CSGO-Market-Float-Finder#1]
After logging in for the first time the program needs to be reopened before it will process anything.

**Comment by sanderpuh** [comment]
Hey! After I login I can search the market, but when I press start it states I have to login again. Also every time I login I have to use an authentication key from Steam to be able to login, it doesn't store it in the .bin file for some reason.

**Comment by adamb70** [comment]
What OS are you using and do you definitely have CS:GO on the Steam account you are signing in with? You might want to try running the program as administrator just to see if that helps. Also delete the .bin file if there is one, and then try launching the program and signing in again.

When the authentication key is used Steam takes a while to actually register that with your account, so the program sends a test message to Steam checking to receive a float value for a skin. If this message doesn't work then Steam doesn't seem to register your authentication key, so maybe this message is not sending. Once you sign in and use the auth key give the program a minute or two to make sure this message sends before closing.
