### ISSUE TITLE
You are not logged into Steam

### ISSUE THREAD

**Issue by XyleneGaming** [adamb70/CSGO-Market-Float-Finder#10]
![image](https://cloud.githubusercontent.com/assets/8739149/13643651/c7854612-e619-11e5-9140-6066927c9561.png)

I've tried running as administrator but this is the only error message I get when pressing the Start button. Do I need to log out of Steam while doing this? (I should probably add that my friend is playing CS:GO on my account while I'm trying this)

**Comment by adamb70** [comment]
It's usually alright if you're logged into Steam, but playing CS:GO at the same time is probably confusing it. Try again after they've stopped playing.
