### ISSUE TITLE
Error not connected to steam

### ISSUE THREAD

**Issue by Felluz** [adamb70/CSGO-Market-Float-Finder#11]
When I press start it appears an error window telling that I'm not connected to steam.
![screenshot_1](https://cloud.githubusercontent.com/assets/16976344/13906225/115c27f8-eeb0-11e5-82a5-bd0b68455686.jpg)

**Comment by adamb70** [comment]
Have you gone through the sign in process when the program starts, and if so does your Steam account own CS:GO?

**Comment by Felluz** [comment]
I solved the problem temporarily by deleting the file sentry_*****.bin but after using it sometimes it appears again. Answering your question, yes I've signed in and I own CS:GO.

**Comment by adamb70** [comment]
The sentry file gets created after the first time you sign in with a Steam email auth code (it's used so you don't have to input your auth code every time you log in, assuming you're not using mobile auth), but sometimes something can go wrong and deleting it then trying to sign in forces Steam to send you a new auth code to use for that program, which usually fixes the problem.

Do you keep getting the errors every time you sign in even after you've deleted the sentry file and forced it to be recreated?

**Comment by Felluz** [comment]
No, as I said the file appears again and the error seems random, right now I can enter and search, but I don't know if next time I enter will be the same.

**Comment by adamb70** [comment]
The file is supposed to be there, if you can sign in now then the file should be working fine and you can leave it as is.
