### ISSUE TITLE
can you help me,how can i fix this?

### ISSUE THREAD

**Issue by pumpdude** [adamb70/CSGO-Market-Float-Finder#13]
<img src="http://i12.tietuku.cn/b52e0f3194c40720.png"/>
already used py2.7 py3.3(x86&x64) py3.4 pyside1.2.4 pyinstaller3.1.1, still cant compile a porper exe file, would you tell me how to setup my development environment?

**Comment by adamb70** [comment]
I'm using x64 py2.7, pyside 1.2.2, and pyinstaller 2.1.

The compiling should be as simple as downloading the full source code, then running `>pyinstaller "CSGO Market Float Finder.spec"`.

The other packages that the program uses are:

```
crypto==1.4.1
gevent==1.0.2
greenlet==0.4.9
protobuf==2.6.1
requests==2.5.1
Werkzeug==0.11.2
```

I think that's all you should need for it.

**Comment by pumpdude** [comment]
thank you,i fix it
