### ISSUE TITLE
Impossible to start

### ISSUE THREAD

**Issue by lerayj** [adamb70/CSGO-Market-Float-Finder#15]
When clicking on start after retrieve items, error message popup say I'm not connected to Steam.

Is that normal?

**Comment by DaveLV24** [comment]
I have same problem, please fix it :/

**Comment by adamb70** [comment]
Are you using Steam 2 factor authentication, and does the sign in process when the program starts complete? Also make sure you aren't currently playing CS:GO from your Steam account when trying to parse data.

**Comment by adamb70** [comment]
Please download the latest version (2.3.0) and enable logging in the settings with `logging=2`. 

Assuming this version didn't fix your problem please share the log here so I can try and figure out what is wrong.
