### ISSUE TITLE
BS Items no longer work?

### ISSUE THREAD

**Issue by ghost** [adamb70/CSGO-Market-Float-Finder#16]
When putting in a BS link it says there is a connection error, and that you should check the URL/connect to the internet.
I can look up any non-BS items.

http://i.imgur.com/HkSCavq.png

**Comment by adamb70** [comment]
It's all working fine on my end, so you might be having a problem with localisation or URL escaping.

Can you enable debugging in the `settings.txt` file (`logging=1`) and try again? You should get a log output in `log.txt` and there might be something in there that can help us.

**Comment by ghost** [comment]
I did a bit more testing, what I found was items like these work;
http://steamcommunity.com/market/listings/730/Five-SeveN%20%7C%20Case%20Hardened%20%28Battle-Scarred%29
http://steamcommunity.com/market/listings/730/Desert%20Eagle%20%7C%20Kumicho%20Dragon%20%28Battle-Scarred%29
 Notice how there are no brackets around Batte-Scared.

But items like these do not work;
https://steamcommunity.com/market/listings/730/AWP%20%7C%20Asiimov%20(Battle-Scarred)
https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Redline%20(Battle-Scarred)
Notice that there are brackets around BS.

I attached the log file:
[log.txt](https://github.com/adamb70/CSGO-Market-Float-Finder/files/403940/log.txt)

I have used this program on a different computer, and this bug did not exist.

**Comment by adamb70** [comment]
Thanks for all the info, it makes it much easier to debug. I'm wondering if maybe its the `https://` bit that is the problem, not the brackets. Can you try these links? They're the same as the ones that don't work but using `http://` instead.

```
http://steamcommunity.com/market/listings/730/AWP%20%7C%20Asiimov%20(Battle-Scarred)
http://steamcommunity.com/market/listings/730/AK-47%20%7C%20Redline%20(Battle-Scarred)
```

**Comment by ghost** [comment]
I didn't notice that the `http://`  part differs before, but that has fixed the problem! Thanks!
