### ISSUE TITLE
Can't login at all

### ISSUE THREAD

**Issue by don0tdisturb** [adamb70/CSGO-Market-Float-Finder#2]
It seems that the program will not login at all. Using Windows 10 x64, tried as admin/non-admin.

Maybe it's not updated after the mobile authenticator implementation?

Hope you can give some info on this. Regards :)

**Comment by adamb70** [comment]
Thank you for bringing this to my attention, I haven't been keeping up to date with the new Steam authentication. I will have a go at getting it fixed for later this week.

**Comment by don0tdisturb** [comment]
Thank you, it would be great to have it working again.

Let me know if you need some help with testing :)

Regards!

**Comment by adamb70** [comment]
Should be working now in the new version, thanks for letting me know! :)
