### ISSUE TITLE
CSGO float value request

### ISSUE THREAD

**Issue by Yakuho** [adamb70/CSGO-Market-Float-Finder#22]
Hi. Thank you for ur donation. I would like to know whether the floating value of CSGO weapon is requested to the STEAM server with TCP. Is it sitll work if I don't log in ??

**Comment by adamb70** [comment]
Won't work if you're not logged in. It uses [SteamKit](https://github.com/SteamRE/SteamKit) to communicate with the Steam servers from your account as if you were playing the game, so it also requires you to own the game on your steam account.

I also haven't updated or used it in many years, so I don't know for sure if it still works.
