### ISSUE TITLE
Doesnt work as of 27.1.16

### ISSUE THREAD

**Issue by itselite** [adamb70/CSGO-Market-Float-Finder#3]
While trying to log in with valid details it keeps complaining about wrong password or username. I tried lots of things but It doesn't seem to lead me to the authentication part where I could insert my authentication code. I'm curious as to why this happens and if there is a possible fix to it?

**Comment by CGMentos** [comment]
doesnt work as of 31.1.16

**Comment by adamb70** [comment]
This could be due to [this issue](https://github.com/adamb70/CSGO-Market-Float-Finder/issues/2) mentioned the other week. I am working on implementing the new authentication method now, so try again after that.

**Comment by adamb70** [comment]
New version is up, please try that one. You can re-open this issue or create a new one if it still won't work.
