### ISSUE TITLE
If Chinese user can't work , please see this

### ISSUE THREAD

**Issue by CGMentos** [adamb70/CSGO-Market-Float-Finder#5]
其实一直可以用，不过首先要保证你的目录路径是全英文。

如果一直提示你需要sign in才能用，那么请看下面：
登录到界面之后输出一个.csv文件，就左上角的file，具体步骤就不用说了。
然后正常使用直到提示"need sign in"，重启，登录，弹出窗口提示“success sign in”为止。
这工具毕竟免费，读取速度非常慢，而且容易出BUG

**Comment by adamb70** [comment]
Thanks for your help. If anybody knows a way to fix this please let me know.

**Comment by zcxkkk** [comment]
楼主你好，请问你知道单个武器的Float Value是怎么计算出来的么，我是写php的所以暂时看不懂python。。
是通过哪个steam api还是有公式计算出来的？非常感谢

**Comment by adamb70** [comment]
Hi, to find an individual float value you can use [this method](https://github.com/Tewki/CSGO-Item-Floats-From-Inspect-Links). I do not know how it can be done using PHP though, because there is no SteamKit port for PHP.
