### ISSUE TITLE
can't pull floats with limited account

### ISSUE THREAD

**Issue by rozepoy** [adamb70/CSGO-Market-Float-Finder#6]
having issues. i can log in just fine but pressing "retrieve items" just doesn't do anything. account is limited, so can't buy/sell on market, but has 1 game and it can access steam api. what is the issue and how can it be fixed? does my account need to be unlimited and able to purchase from market?

also, would it be possible to implement a feature to sign in with steam without inputting password? seems much safer and doesn't seem hard to implement, though i lack the knowledge.

**Comment by adamb70** [comment]
You need to use an account that owns CS:GO otherwise it will not work. This program does not deal with purchasing/selling, nor the Steam API, so a limited account shouldn't affect this program. 

Also there is no way to sign into Steam without inputting a password.
