### ISSUE TITLE
How to use with mobile authenticater

### ISSUE THREAD

**Issue by mvoellmy** [adamb70/CSGO-Market-Float-Finder#8]
Hey man, I really like the app. Is there a way to use the app without having to disable the mobile authenticator?
Cheers

**Comment by adamb70** [comment]
It should work with the mobile authenticator. When you enter your login details into the app you should see a popup window asking you to enter your mobile two-factor authentication code, do you not get this window?
![window](https://cloud.githubusercontent.com/assets/11885987/13636497/2aaeb5a4-e5fa-11e5-9a4a-a9ebc44d0655.PNG)

**Comment by mvoellmy** [comment]
Using the .exe I never got this popup. I downloaded the app a few months ago.

**Comment by adamb70** [comment]
That will be the old version before Steam implemented 2FA then, try downloading the program again to get the newest version :)

**Comment by mvoellmy** [comment]
Alright thanks. :+1: :)
